name: Prabal Gupta's Blog
title: Prabal Gupta | Some cool stuffs to read 
description: Prabal Gupta is professionally a CS undergraduate student
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: prabalgupta4343@gmail.com
disqus_username: prabalgupta1mv18cs066
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email : prabalgupta4343@gmail.com
disqus_username: prabalgupta1mv18cs066